name: bbuzz.me
favicon: null
layout_spectrum: 0.84287
typography_spectrum: 0.72177
title: Online Magazine
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-41841548-14
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0b0b08'
    - '#004789'
    - '#0094fc'
    - '#999998'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
